#! /bin/bash

###
# Transfer code files via sftp to the Pi and automatically compile/run them. Goal is to automate coding
# on my local machine and running on the Pi
#
# Added with sudo visudo /etc/sudoers a line :
# mr	ALL=(root) NOPASSWD: /home/mr/mrProj2/build/*
#
# Added as function to my zsh shell, function name run $1=file
# #~/.zsh/.zshrc : fpath+=/Users/urban/.zsh/.zsh_functions
# #autoload run
# function definition in .zsh_functions: file run, content:
# function run {
# readonly file=${1:?"The file must be specified."}
# readonly isClass=$2
#
# /Users/urban/Documents/MobileRobotics/4Semester/_Skripte/ROS/mrProj2/shellScripts/sftpToPi_run $file $2
# }
#
# author: urban
###

# Variables
remotePath="/home/mr/mrProj2/source/"
execPath="/home/mr/mrProj2/build/"
execName="ioExp_dev"

file=$1
isClass=$2

localFile=$(realpath $file)
remoteFile=$remotePath/src/$file

if [[ $file != *"."* ]] # contains no point
then
	isClass=c
fi

# if positional argument class is c for class, copy .cpp and .h file to pi but do not compile
if [ "$isClass" == "c" ]
then
	localClassname=${localFile%.*}
	
	scp $localClassname.h pi:$remotePath/inc
	scp $localClassname.cpp pi:$remotePath/src

# else run normal program
else
	executable=${file%.*} # executable name = filename without .extension
	extension=${file#*.}
	
	if [ "$extension" == "cmake" ]
	then
		scp $localFile pi:$remotePath/CMakeLists.txt # Change name of destination file
		ssh pi "cd $execPath && cmake --build . --config Release --target $execName"
		echo "===========================Runtime=============================="
		ssh pi "sudo $execPath$execName"
		exit
	fi
	
	scp $localFile pi:$remotePath/src

	if [ "$extension" == "c" ]
	then
		clear
		# note the double quotation marks, with single variables not evaluated before sending.
		ssh pi "gcc -Wall -o $execPath$executable $remoteFile -lpigpio" # sometimes doesn't work, but executing directly on raspi works fine.
		ssh pi "sudo $execPath$executable"
	fi

	if [ "$extension" == "cpp" ]
	then
		echo "run makefile to build and execute program."
		#clear
		#ssh pi "g++ -Wall -Wextra -o $execPath$executable $remoteFile -lpigpio"
		#ssh pi "sudo $execPath$executable"
	fi	
fi
