#! /bin/bash

###
# Transfer code files via sftp to the Pi and automatically compile/run them. Goal is to automate coding
# on my local machine and running on the Pi
#
# Added as function to my zsh shell, function name run $1=file
# #~/.zsh/.zshrc : fpath+=/Users/urban/.zsh/.zsh_functions
# #autoload run
# function definition in .zsh_functions: file run, content:
# function run {
# readonly file=${1:?"The file must be specified."}
#
# /Users/urban/Documents/MobileRobotics/4Semester/_Skripte/ROS/mrProj2/shellScripts/sftpToPi $file
# }
#
# author: urban
###

# Variables
remotePath="/home/mr/mrProj2/src/"

#echo -e "File to be transferred : "
#read -e file

file=$1

localFile=$(realpath $file)
remoteFile=$remotePath$file

sftp pi <<EOT
put $localFile $remotePath
chmod 744 $remoteFile #make executable
bye
EOT

clear

ssh -T pi <<EOT # suppress warning no console connection via this script
$remoteFile
exit
EOT
